name: Sync Fork

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Sync and merge upstream repository with your current repository
        uses: dabreadman/sync-upstream-repo@v1.3.0
        with:
          # URL of gitHub public upstream repo
          upstream_repo: https://github.com/apache/dubbo.git
          # Branch to merge from upstream (defaults to downstream branch)
          upstream_branch: 3.3
          # Branch to merge into downstream
          downstream_branch: 3.3
          # GitHub Bot token
          # token: ${{secrets.GITHUB_TOKEN}}
          token: ${{secrets.REPO_SYNC_TOKEN}} #NEW TOKEN ADDED FOR ORG WITH WORKFLOW PERMISSION
